---
# tasks file for apache
- name: Install httpd
  package:
   name: "{{package_name}}"
   state: present

- name: Start httpd daemon
  systemd:
   name: "{{package_name}}"
   state: started
   enabled: true

- name: Copy Index file to server
  copy:
   src: index.html
   dest: /var/www/html/index.html

  notify:
   - Restart Apache
