---
- hosts: db
  become: true
  gather_facts: 0
  tasks:
    - name: Update server
      yum:
        name: '*'
        state: latest
      tags:
        - update  
    - name: Install Apache
      package:
        name: httpd
        state: present
      tags:
        - install
    - name: Start services
      systemd:
        name: httpd
        state: started
        enabled: yes
      tags:
        - daemon
    - name: Copy Index file to server
      copy: 
        src: index.html
        dest: /var/www/html/index.html
      tags:
        - file_copy
      notify: 
        - Restart Apache


  handlers:
    - name: Restart Apache
      systemd: 
        name: httpd
        state: restarted


#yum update -y
#yum install httpd -y
#systemctl start httpd
#systemctl enable httpd
#cd /var/www/html
#touch index.html
#vi
