---
- hosts: db
  become: true
  gather_facts: false
  tasks:
    - name: Install Packages
      yum:
        name: "{{ item }}"
        state: present
#     with_items: or use loop
      loop:
        - curl
        - finger
        - wget
        - httpd
        - ntp
